export const FIELD_GROUPS: Record<string, string[]> = {
    'Информация о заказе': [
        'ShipmentMonth',
        'ShipmentYear',
        'OrderDate',
        'OrderConformDay',
        'RunOrderDay',
        'OrderShipmentDay_Svod',
        'ProductionOrder',
        'Order_No',
        'Market',
        'Delay',
    ],
    'Информация о продукте': [
        'Prod_Group',
        'GroupName',
        'Article_number',
        'Name_CN',
        'Firmware',
        'HeadAndOther',
        'Power',
        'Displacement',
    ],
    'Кол-во': [
        'Total_Order_QTY',
        'Order_QTY',
        'FACT_QTY',
        'Uncompleted_QTY',
    ],
}; 